### PR TITLE
Remove check on PL values when computing local alleles

### LINKED ISSUE #277: LPL no smaller than PL
After running conversion on 1000 Genomes chr2 data, I'm not seeing any reduction in the size of PL fields. Here's the ICF:

```
$ vcf2zarr inspect 1kg_chr2_lpl.icf/ | grep PL
FORMAT/PL                 Integer      6906  430.58 GiB  60.6 GiB           28  0          3.2e+05
FORMAT/LPL                Integer      6906  430.58 GiB  60.57 GiB          28  -1         3.2e+05
$ vcf2zarr inspect 1kg_chr2_lpl.icf/ | grep 'LAA'
FORMAT/LAA                Integer      4534  282.07 GiB  315.18 MiB          6  -2         6
```
and on the VCZ: (for a small number of variants using --max-variant-chunks)
```
$ vcf2zarr inspect 1kg_chr2_lpl.vcz/ | grep PL
/call_LPL                     int32    8.27 MiB    342.01 MiB   41             40  8.55 MiB      211.78 KiB          (1000, 3202, 28)  (100, 1000, 28)  Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   None
/call_PL                      int32    8.27 MiB    342.01 MiB   41             40  8.55 MiB      211.78 KiB          (1000, 3202, 28)  (100, 1000, 28)  Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   None
$ vcf2zarr inspect 1kg_chr2_lpl.vcz/ | grep LAA
/call_LAA                     int8     102.69 KiB  18.32 MiB   180             40  469.04 KiB    2.57 KiB            (1000, 3202, 6)   (100, 1000, 6)   Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   None
```

So, there's no reduction in the maximum dimension and the storage sizes are essentially identical. 

Have you any ideas what might be going on here @Will-Tyler?

I think it would be really worthwhile getting some truth data for LPL that we could compare with. It does seem that getting running Hail is the only way to do this, so probably worth the effort.

### PR DESCRIPTION
**Pull request by jeromekelleher**
WIP - hopefully closes #277

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Just disabling the check on PL values doesn't seem to help, so I took out the check on AD also. We should just be getting back the GTs now. This does definitely help:
```
jk@holly$ python3 -m bio2zarr vcf2zarr inspect tmp/chr22.vcz/ 
name                          dtype    stored      size          ratio    nchunks  chunk_size    avg_chunk_stored    shape              chunk_shape        compressor                                                      filters
----------------------------  -------  ----------  ----------  -------  ---------  ------------  ------------------  -----------------  -----------------  --------------------------------------------------------------  ------------
/call_PL                      int32    497.99 MiB  25.21 GiB     52            30  860.44 MiB    16.6 MiB            (96514, 2504, 28)  (10000, 1000, 28)  Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   None
/call_LPL                     int32    315.14 MiB  5.4 GiB       18            30  184.38 MiB    10.5 MiB            (96514, 2504, 6)   (10000, 1000, 6)   Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   None
/call_AD                      int16    196.58 MiB  3.15 GiB      16            30  107.56 MiB    6.55 MiB            (96514, 2504, 7)   (10000, 1000, 7)   Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   None
/call_DP                      int16    112.11 MiB  460.95 MiB     4.1          30  15.37 MiB     3.74 MiB            (96514, 2504)      (10000, 1000)      Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   None
/call_GQ                      int8     58.65 MiB   230.48 MiB     3.9          30  7.68 MiB      1.95 MiB            (96514, 2504)      (10000, 1000)      Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   None
/call_AB                      float32  30.97 MiB   921.9 MiB     30            30  30.73 MiB     1.03 MiB            (96514, 2504)      (10000, 1000)      Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   None
/call_PID                     object   8.64 MiB    1.8 GiB      210            30  61.46 MiB     295 KiB             (96514, 2504)      (10000, 1000)      Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   [VLenUTF8()]
/call_LAA                     int8     8 MiB       460.95 MiB    58            30  15.37 MiB     273.23 KiB          (96514, 2504, 2)   (10000, 1000, 2)   Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   None
/call_genotype                int8     7.8 MiB     460.95 MiB    59            30  15.37 MiB     266.26 KiB          (96514, 2504, 2)   (10000, 1000, 2)   Blosc(cname='zstd', clevel=7, shuffle=BITSHUFFLE, blocksize=0)  None
/call_PGT                     object   6.74 MiB    1.8 GiB      270            30  61.46 MiB     230.1 KiB           (96514, 2504)      (10000, 1000)      Blosc(cname='zstd', clevel=7, shuffle=NOSHUFFLE, blocksize=0)   [VLenUTF8()]
```
I don't think we've quite got it right though, because if we're just doing local alleles based on the genotypes, the local alleles should all be biallelic and therefore the LPL field should have dimension 3. So there's definitely problems, but we're on the right track.

**Comment by Will-Tyler** [comment]
> therefore the LPL field should have dimension 3

In the case where the LAA has two alternate alleles, vcztools outputs 6 LPL values because the reference allele is always "included". This is necessary because the LAA field does not indicate whether the reference allele is included or not.

See LAA definition in [VCF 4.5](https://samtools.github.io/hts-specs/VCFv4.5.pdf).

**Comment by jeromekelleher** [comment]
Aha yes, that's true, good point. I don't know why the VCF standard decided to list just the non-ref alleles, that seems like an obvious waste here. Oh well, that's the standard, there's no point in thinking too hard about it.

> Happy to finish the fix you started.

If you could pick this up and fix the tests that would be super helpful, thanks @Will-Tyler !

**Comment by jeromekelleher** [comment]
Superseded by  #286

**Pull request closed without merging**
